export const ADD_PLACE = 'ADD_PLACE';
export const LIST_TASKS = 'LIST_TASKS';
export const ADD_TASK = 'ADD_TASK';
export const DELETE_TASK = 'DELETE_TASK';

export const SAVE_USER = 'SAVE_USER';
export const SAVE_USER_FAIL = 'SAVE_USER_FAIL';
export const CLEAN_USER = 'CLEAN_USER';

export const LIST_GROUPS = 'LIST_GROUPS';
export const ADD_GROUP = 'ADD_GROUP';
export const DELETE_GROUP = 'DELETE_GROUP';
export const LIST_GROUPS_REJECTED = 'LIST_GROUPS_REJECTED';
export const ADD_GROUP_REJECTED = 'ADD_GROUP_REJECTED';
export const DELETE_GROUP_REJECTED = 'DELETE_GROUP_REJECTED';
export const SELECTED_GROUP_TASKS = 'SELECTED_GROUP_TASKS';

export const SET_SELECTED_ITEM_ID = 'SET_SELECTED_ITEM_ID';

export const UPDATE_TASK = 'UPDATE_TASK';
export const UPDATE_TASK_REJECTED = 'UPDATE_TASK_REJECTED';
